version: "3.3"

services:
  cams-db:
    restart: always
    build: db
    image: cams-db
    ports:
      - "55433:5432"
    volumes:
      - cams-db:/var/lib/postgresql/data/pgdata
    networks:
      - backend_alpha
    environment:
      - POSTGRES_DB=cams
      - POSTGRES_USER=cams
      - POSTGRES_PASSWORD=cams
      - PGDATA=/var/lib/postgresql/data/pgdata

  cams-api:
    build:
        context: ..
        dockerfile: cams-docker/server/Dockerfile
    image: cams-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=alpha
    networks:
      - frontend_alpha
      - backend_alpha
    depends_on:
      - cams-db

  cams-client:
    build:
      context: ..
      dockerfile: cams-docker/client/Dockerfile
    image: cams-client
    networks:
      - frontend_alpha
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cams-api

networks:
  frontend_alpha:
    driver: bridge
  backend_alpha:
    driver: bridge

volumes:
  cams-db:
