version: "3.3"

services:
        #  cams-db:
        #restart: always
        #build: db
        #image: cams-db
        #    ports:
        #      - "55433:5432"
        #    volumes:
        #      - cams-db:/var/lib/postgresql/data/pgdata
        #    networks:
        #      - backend_alpha
        #    environment:
        #      - POSTGRES_DB=cams
        #      - POSTGRES_USER=cams
        #      - POSTGRES_PASSWORD=cams
        #      - PGDATA=/var/lib/postgresql/data/pgdata

  cams-api:
    build:
        context: ..
        dockerfile: cams-docker/server/Dockerfile
    image: cams-api
    ports:
      - "8181:8181"
    environment:
      - SPRING_PROFILES_ACTIVE=azure
    networks:
      - cams-network
        #    depends_on:
        #- cams-db

  cams-client:
    build:
      context: ..
      dockerfile: cams-docker/client/Dockerfile
    image: cams-client
    networks:
      - cams-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cams-api

networks:
  cams-network:
     driver: bridge
      # volumes:
      #cams-db:
